environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # For faster CI builds

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# scripts that run after cloning repository
install:
 - ps: Import-Module .\appveyor.psm1; Invoke-AppveyorInstall

# scripts to run before build
before_build:
  - dotnet --info

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ps: .\build.ps1 --target=AppVeyor

# scripts to run after build
after_build:

# Tests
test: off

# Branches to build
branches:
  only:
    - develop
    - master
    - main
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - tools -> build.cake

# Environment configuration
image: Visual Studio 2022

#  Skip builds for doc changes
skip_commits:
  message: /\(doc\).*/
